### PR TITLE
Jdev

### PR DESCRIPTION
**Pull request by itsOwlbit**
- added .devcontainer
- added .vscode
- made changes to other files (utils) because of an error of not found
- added debug.yml at root along with files in compose/local/debug

Current error when trying to load the page is:
```
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8001'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
```
Same with:
```
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'localhost:8001'. You may need to add 'localhost' to ALLOWED_HOSTS.
```

Before attempting to load 127.0.0.1:8001/stoqs:
```2023-07-20 17:05:03 Performing system checks...
2023-07-20 17:05:03 
2023-07-20 17:05:04 System check identified no issues (0 silenced).
2023-07-20 17:05:04 
2023-07-20 17:05:04 Django version 4.2.2, using settings 'config.settings.local'
2023-07-20 17:05:04 Development server is running at http://0.0.0.0:8001/
2023-07-20 17:05:04 Using the Werkzeug debugger (http://werkzeug.pocoo.org/)
2023-07-20 17:05:04 Quit the server with CONTROL-C.
2023-07-20 17:05:04  * Debugger is active!
2023-07-20 17:05:04  * Debugger PIN: 974-635-825
```

Also, when trying to attach to the stoqs running container inside VSCode, the opened window contained no files.  I was not able to test if debugging with a devcontainer works.

### CODE REVIEW

**Comment by itsOwlbit** [comment]
Added Drew's debugpy to this branch.  Works as expected.

**Comment by itsOwlbit** [comment]
- Change DEBUG=1 on .env to use debugpy.  Right now it is set to 0.
- Changed the debugpy code to be more together.
- Commented out 4 tests that hang due to x3dom.
- Changed template/stoqs/stoqsquery.html so that xdom3.org is not called.  Added the x3dom.css file to static/x3dom-1.8.1 folder.

41 tests are found since 4 tests are commented out.  One test has error.  I found that the name entry it was looking for in the stoqs_parameter table and it was not found.  Below is the error:
```
stoqs            | ======================================================================
stoqs            | ERROR: test_sampledparameter_select (stoqs.tests.unit_tests.SummaryDataTestCase)
stoqs            | ----------------------------------------------------------------------
stoqs            | Traceback (most recent call last):
stoqs            |   File "/srv/stoqs/tests/unit_tests.py", line 341, in test_sampledparameter_select
stoqs            |     CAL1939_calanoida_id = Parameter.objects.get(name='CAL1939_calanoida').id
stoqs            |   File "/usr/local/lib/python3.10/dist-packages/django/db/models/manager.py", line 87, in manager_method
stoqs            |     return getattr(self.get_queryset(), name)(*args, **kwargs)
stoqs            |   File "/usr/local/lib/python3.10/dist-packages/django/db/models/query.py", line 637, in get
stoqs            |     raise self.model.DoesNotExist(
stoqs            | stoqs.models.Parameter.DoesNotExist: Parameter matching query does not exist.
stoqs            |
stoqs            | ----------------------------------------------------------------------
```

**Comment by itsOwlbit** [comment]
Functional tests finally work.  10 tests.  1 error.
```
======================================================================
ERROR: test_share_view_timeseries (stoqs.tests.functional_tests.BrowserTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/srv/stoqs/tests/functional_tests.py", line 325, in test_share_view_timeseries
    self._test_share_view('test_m1_timeseries')
  File "/srv/stoqs/tests/functional_tests.py", line 175, in _test_share_view
    self.browser.get(permalink_url)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 355, in get
    self.execute(Command.GET, {"url": url})
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 346, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidArgumentException: Message: invalid argument
  (Session info: chrome=102.0.5005.61)
Stacktrace:
#0 0x555555bb7f33 <unknown>
#1 0x555555901faf <unknown>
#2 0x5555558ed498 <unknown>
#3 0x5555558ebe62 <unknown>
#4 0x5555558ec042 <unknown>
#5 0x555555903b92 <unknown>
#6 0x555555969a3f <unknown>
#7 0x555555955f72 <unknown>
#8 0x5555559692e4 <unknown>
#9 0x555555955e63 <unknown>
#10 0x55555592b82a <unknown>
#11 0x55555592c985 <unknown>
#12 0x555555bfc4cd <unknown>
#13 0x555555c005ec <unknown>
#14 0x555555be671e <unknown>
#15 0x555555c01238 <unknown>
#16 0x555555bdb870 <unknown>
#17 0x555555c1d608 <unknown>
#18 0x555555c1d788 <unknown>
#19 0x555555c37f1d <unknown>
#20 0x7ffffffa6609 <unknown>
```
I will take that.  

I am placing instruction in the next comment.

**Comment by itsOwlbit** [comment]
Instructions for running functional tests.

NOTE: Make sure .env DJANGO_DEBUG=false

Take down all images:
 ```
docker-compose -f local-ci.yml down
```

Build and run local-ci.yml detached mode:
```
docker-compose -f local-ci.yml up -d --build
```

Run whatever this is:
```
docker-compose -f local-ci.yml run --rm stoqs /bin/bash
```

Now you should be in the bash.

Start the functional test:
```
DATABASE_URL=$DATABASE_SUPERUSER_URL python manage.py test stoqs.tests.functional_tests --settings=config.settings.ci
```

Open browser to:
```
http://localhost:7900/?autoconnect=1&resize=scale&password=secret
```

And let selenium take control.  Takes approximately 5 minutes to complete.

After watching the show, you can hit control + c a million times to stop it so you can type exit to exit the shell.  The containers are still running so you have to deal with that still.  Maybe need to down all the containers and rebuild local.yml for development environment when done testing.

**Review by olivesdad — APPROVED** [review]
LGTM

I was able to successfully run the tests

**Review by olivesdad — APPROVED** [review]
I approve this message

**Pull request merged**
